# This is a basic workflow to help you get started with Actions
name: Build LaTeX document
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: papers/main.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
